
[[constraint]]
  name = "github.com/codegangsta/cli"
  version = "^1.20.0"

[[constraint]]
  name = "github.com/shurcooL/vfsgen"

[[constraint]]
  name = "github.com/mnbbrown/mailchimp"

[[constraint]]
  name = "github.com/nlopes/slack"
